### ISSUE TITLE
[Question] Why `enableInfiniteScroll` of `ExpandableCarouselController` is commented?

### ISSUE THREAD

**Issue by jttuboi** [nixrajput/flutter_carousel_widget#52]
Hi, I'm looking for a carousel widget and I found this package. I think this is the most complete widget I found, thanks. But I'm looking for an widget as ExpandableCarousel with a loop (or infinite scroll).

I've looked your code and I've found the parameter `enableInfiniteScroll` of `ExpandableCarouselController` is commented. Is there a bug to fix after, because this you commented? Is there a deadline to delivery this feature?
> <img width="1009" alt="image" src="https://github.com/user-attachments/assets/cc664010-2f92-40f4-977a-d9bc1abfb745">

<br>
<br>
<br>

One observation. In the issue page, the `Code of Conduct` link is broken (in `Bug report` and `Feature request`).
> <img width="597" alt="image" src="https://github.com/user-attachments/assets/55ebf1e8-bbd1-4c31-91c3-170225466ae4">
> <img width="842" alt="image" src="https://github.com/user-attachments/assets/19edd378-fe2b-4119-ba51-41b756d6e1a1">

**Comment by nixrajput** [comment]
Hi @jttuboi,

Thank you for using the package and for your kind words.

The `enableInfiniteScroll` property of `ExpandableCarouselController` is currently commented out because, during the last update, I discovered that it wasn't functioning correctly and was causing issues in the widget.

This feature will be re-enabled once I, or someone from the GitHub community, address and fix the issue. At the moment, I’m unable to dedicate time to work on this package due to personal commitments, but I aim to resolve the issue by the end of this month.

I will also update the link to the `Code of Conduct` in the `Bug report` and `Feature request` sections. Thank you for bringing this to my attention.

Best regards,  
Nikhil
